version: 2.0.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_tags: true
max_jobs: 1
image: Ubuntu
clone_depth: 1
build_script:
- sh: |-
    set -euo pipefail

    export DOCFX_SOURCE_BRANCH_NAME="${APPVEYOR_REPO_BRANCH}"

    echo "Build: ${APPVEYOR_BUILD_NUMBER} / Branch: ${APPVEYOR_REPO_BRANCH}"
    echo "Commencing build"
    ./release --artifacts ./artifacts --configuration Release --version-suffix dev --build-number "${APPVEYOR_BUILD_NUMBER}"
    
dotnet_csproj:
  patch: true
  file: '**/*.csproj'
  version: $(appveyor_build_version)
  package_version: $(appveyor_build_version)
  assembly_version: $(appveyor_build_version)
  file_version: $(appveyor_build_version)
  informational_version: $(appveyor_build_version)

artifacts:
- path: artifacts/*.nupkg

test_script:
  - sh: ./test --configuration Release --no-restore --no-build

deploy:
- provider: NuGet
  api_key:
    secure: FBNj2AVj/zdWXSelRKh9u5IceHXlvTEssLN+aOTjin41RIENm8s7l7gOMDi/RezW   # Encrypted NuGet ey in AppVeyor (Account -> Encrypt YAML)
